# Generated by Django 3.2.9 on 2021-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=100)),
                ('scientificName', models.CharField(default='', max_length=100, null=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('unitPrice', models.FloatField(default=0, max_length=10)),
                ('storageTemperature', models.FloatField(default=0, max_length=6, null=True)),
                ('dangerousLevel', models.CharField(default='', max_length=100, null=True)),
                ('storageLocation', models.CharField(default='', max_length=100, null=True)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
