# Generated by Django 3.2.9 on 2021-11-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(default='Shop - No name', max_length=100)),
                ('mobilePhone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='Address - No name', max_length=500)),
                ('city', models.CharField(default='Address - No city', max_length=500)),
                ('ratings', models.FloatField(default=0, max_length=3, null=True)),
            ],
            options={
                'ordering': ['shopName'],
            },
        ),
        migrations.CreateModel(
            name='StoredDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batchNo', models.FloatField(default=0, max_length=10)),
                ('manufacturingDate', models.DateField()),
                ('expireDate', models.DateField()),
                ('quantity', models.FloatField(default=0, max_length=10)),
                ('drugId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.drugs')),
                ('shopName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.shop')),
            ],
            options={
                'ordering': ['drugId'],
            },
        ),
    ]
