# Generated by Django 3.2.9 on 2021-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_shop_storeddrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeddrug',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
