# Generated by Django 3.2.9 on 2021-11-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_alter_storeddrug_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeddrug',
            old_name='shopName',
            new_name='shopId',
        ),
    ]
