# Generated by Django 3.2.9 on 2021-11-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_rename_shopname_storeddrug_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.FloatField(default=0, max_length=10)),
                ('offerTill', models.DateField()),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.shop')),
            ],
        ),
    ]
