# Generated by Django 3.2.9 on 2021-11-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_shopoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopoffer',
            options={'ordering': ['offerTill']},
        ),
        migrations.RemoveField(
            model_name='shopoffer',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pp.shop'),
        ),
    ]
