# Generated by Django 3.2.9 on 2021-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20211128_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopoffer',
            name='offer',
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='offerInPercentage',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopoffer',
            name='offerInTaka',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
