# Generated by Django 3.2.9 on 2021-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0007_auto_20211128_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopoffer',
            name='offerInPercentage',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='shopoffer',
            name='offerInTaka',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
    ]
