# Generated by Django 3.2.9 on 2021-11-29 09:51

from django.db import migrations, models
import pp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0008_auto_20211128_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopImg',
            field=models.ImageField(blank=True, null=True, upload_to=pp.models.shop_img_upload_path),
        ),
    ]
