# Generated by Django 3.2.9 on 2021-11-29 10:31

from django.db import migrations, models
import pp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0009_shop_shopimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='drugImg',
            field=models.ImageField(blank=True, null=True, upload_to=pp.models.drug_img_upload_path),
        ),
    ]
