# Generated by Django 3.2.9 on 2021-11-29 11:08

from django.db import migrations, models
import pp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0010_drugs_drugimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drugImg',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to=pp.models.drug_img_upload_path, width_field=800),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopImg',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to=pp.models.shop_img_upload_path, width_field=800),
        ),
    ]
