# Generated by Django 3.2.9 on 2021-12-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0013_auto_20211129_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['ratings']},
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(default='None', max_length=254, null=True),
        ),
    ]
