# Generated by Django 3.2.9 on 2021-12-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0016_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
