# Generated by Django 3.2.9 on 2021-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0017_remove_contactus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
