# Generated by Django 3.2.9 on 2021-12-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0019_rename_name_contactus_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='scientificName',
        ),
        migrations.AlterField(
            model_name='shop',
            name='mobilePhone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ratings',
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
    ]
