# Generated by Django 3.2.9 on 2021-12-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0020_auto_20211220_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='dangerousLevel',
            new_name='ageLevel',
        ),
        migrations.AlterField(
            model_name='shop',
            name='ratings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
