# Generated by Django 3.2.9 on 2021-12-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0021_auto_20211220_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField(default=-1)),
                ('userId', models.IntegerField(default=-1)),
                ('comment', models.CharField(default='Default Comment', max_length=255)),
            ],
            options={
                'ordering': ['shopId'],
            },
        ),
    ]
