# Generated by Django 3.2.9 on 2021-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0022_shopreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='commentUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
