# Generated by Django 3.2.9 on 2021-12-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0023_shopreview_commentupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugId', models.IntegerField(default=-1)),
                ('userId', models.IntegerField(default=-1)),
                ('comment', models.CharField(default='Default Comment', max_length=255)),
                ('commentUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['commentUpdated'],
            },
        ),
        migrations.AlterModelOptions(
            name='shopreview',
            options={'ordering': ['commentUpdated']},
        ),
    ]
