# Generated by Django 3.2.9 on 2021-12-23 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0025_remove_drugs_storagelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='timeStampCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='timeStampUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
