# Generated by Django 3.2.9 on 2021-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0027_auto_20211224_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdId', models.IntegerField(default=-1)),
                ('userId', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['userId'],
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['shopName']},
        ),
    ]
