# Generated by Django 3.2.9 on 2021-12-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0030_alter_cart_sdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sdId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.storeddrug'),
        ),
    ]
