# Generated by Django 3.2.9 on 2021-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0031_alter_cart_sdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sdId',
            field=models.IntegerField(default=-1),
        ),
    ]
